"""The static catalog of built-in slash commands.

Phase 9 attaches handlers in a command registry; the names and descriptions
below are the plan's command list and are what the ``/`` picker completes.
Skill-registered commands (``register_cmd: true``) merge on top at runtime.
"""

from __future__ import annotations

#: ``(name, description)`` pairs, in display order.
BUILTIN_COMMANDS: list[tuple[str, str]] = [
    ("new", "Start a new session"),
    ("clear", "Clear the visible transcript"),
    ("resume", "Resume another session"),
    ("session", "Show session info"),
    ("undo", "Hide the last user turn"),
    ("redo", "Restore an undone turn"),
    ("rewind", "Rewind to an earlier point"),
    ("retry", "Retry the last turn"),
    ("rename", "Rename this session"),
    ("history", "Show input history"),
    ("quit", "Exit lecode"),
    ("exit", "Exit lecode"),
    ("handoff", "Hand off to a fresh session with a summary"),
    ("compact", "Compact the context now"),
    ("compress", "Compress tool outputs in context"),
    ("model", "Switch the model"),
    ("models", "List available models"),
    ("models-add", "Add a model preset"),
    ("provider", "Switch the provider"),
    ("thinking", "Set thinking level"),
    ("reasoning", "Toggle reasoning display"),
    ("permissions", "Show permission rules"),
    ("mode", "Switch permission mode"),
    ("toggle", "Toggle a tool on/off"),
    ("prompt", "Switch prompt style/persona"),
    ("editsys", "Edit the system prompt"),
    ("add", "Add a file to context"),
    ("drop", "Drop a file from context"),
    ("drop-all", "Drop all added files"),
    ("init", "Write an AGENTS.md for this project"),
    ("help", "Show help"),
    ("welcome", "Show the welcome message"),
    ("tutor", "Interactive tutorial"),
    ("review", "Review current changes"),
    ("btw", "Side note to the model mid-turn"),
    ("queue", "Show queued/steered messages"),
    ("copy", "Copy the last answer to the clipboard"),
    ("export", "Export the session as HTML"),
    ("import", "Import a session file"),
    ("share", "Share the session via secret gist"),
    ("loop", "Run a loop over a plan file"),
    ("chain", "Run a brainstorm→plan→code→review chain"),
    ("worktree", "Work in a git worktree"),
    ("wt-exit", "Exit the worktree"),
    ("wt-merge", "Merge the worktree back"),
    ("mcp", "Manage MCP servers"),
    ("model-subagent", "Set the subagent model"),
    ("models-subagent", "List subagent models"),
    ("notifications", "Configure audio notifications"),
    ("memory", "Inspect/edit persistent memory"),
    ("advisor", "Ask the advisor model"),
    ("hooks", "Show configured hooks"),
    ("agents", "List agents"),
]
